
export const prompts = [
  'Pixel art sprite of a space marine in power armor, white background',
  'Pixel art icon for a health potion, glowing red, white background',
  'Pixel art of a treasure chest, closed, ornate gold, white background',
  'Pixel art character sprite for a rogue with a dark cloak, daggers drawn, white background',
  'Pixel art of a sci-fi laser pistol asset, white background',
  'Pixel art of a flaming sword icon, 16-bit style, white background',
  'Pixel art sprite of a goblin warrior with a rusty axe, white background',
  'Pixel art of an ancient spellbook, glowing runes, white background',
  'Pixel art tile for a dungeon floor, cracked stone, white background',
  'Pixel art character sprite of a wise old wizard with a long beard, white background',
  'Pixel art asset of a wooden shield with a steel border, white background',
  'Pixel art sprite of a chibi-style hero with a large sword, white background',
  'Pixel art of a stack of gold coins, game asset, white background',
  'Pixel art icon for a mana flask, swirling blue liquid, white background',
  'Pixel art character sprite of an elven archer, longbow ready, white background',
  'Pixel art of a cartoon bomb with a lit fuse, white background',
  'Pixel art sprite of a skeleton enemy, bones showing, white background',
  'Pixel art of a magical staff with a crystal on top, white background',
  'Pixel art asset for a collection of gems, different colors, white background',
  'Pixel art character sprite for a female knight in shining armor, white background',
  'Pixel art of a medieval-style helmet icon, white background',
  'Pixel art sprite of a small, cute slime monster, green, white background',
  'Pixel art of a futuristic energy shield effect, white background',
  'Pixel art icon for a key, ornate and golden, white background',
  'Pixel art character sprite of a barbarian with a giant battle-axe, white background',
  'Pixel art asset of a crate of supplies, wooden, white background',
  'Pixel art sprite of a zombie shambling forward, tattered clothes, white background',
  'Pixel art of a set of leather boots, game inventory icon, white background',
  'Pixel art character sprite of a stealthy ninja, full body, white background',
  'Pixel art icon for a rare magical mushroom, glowing blue, white background',
  'Pixel art of a dragon\'s eye, reptilian, staring, white background',
  'Pixel art sprite of a robot companion, friendly looking, white background',
];
